### ISSUE TITLE
A warning like this appears.

### ISSUE THREAD

**Issue by yopeule** [o175/indent-selection-code#2]
When i run this extension at non-indented area of text editor, this warning appears.

```Running the contributed command: 'select-indentation.expand-selection' failed.```

It doesn't important, but I hope it will be revised someday.

**Comment by o175** [comment]
Shure. I'll try to fix it in a few days

**Comment by yopeule** [comment]
If there is no lower indent around the block, it won't work. For example, a method containing the last line of the file. And global function names etc... Need to handle exceptions for EOF, zero indentation.

**Comment by o175** [comment]
Fixed and published via new publisher id:
o175o.select-indentation
I've lost access to my old one =(
